baseURL = "https://randomcreations.wtf/"
languageCode = "en-us"
title = "Random Creations by @dahljonatan"
theme = "randomcreationstheme"
# open graph:
[params]
  description = "3D art, game development, graphic design, and creative experiments by Jonatan Dahl."
  images = ["/img/archvizblender.png"]

[taxonomies]
  series = "series"
