version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.55
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build static assets
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - public # hugo output
            - package.json
            - firebase.json
  deploy:
    docker:
      - image: cimg/node:16.17
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Print SA key to file
          command: echo $DEPLOY_KEY > ~/key.json
      - run:
          name: Deploy Master to Firebase Hosting
          command: GOOGLE_APPLICATION_CREDENTIALS=~/key.json ./node_modules/.bin/firebase deploy --project randomcreations

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
