version: 2.1

jobs:
  dependencies:
     docker:
       - image: circleci/node:10
     working_directory: ~/app
     steps:
       - run:
           name: Install dependencies
           command: npm install
  build:
     docker:
       - image: cibuilds/hugo:latest
     working_directory: ~/app
     steps:
       - run:
           name: Build static assets
           command: hugo
  deploy:
     docker:
       - image: circleci/node:10
     working_directory: ~/app
     steps:
       - run:
           name: Deploy Master to Firebase Hosting
           command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  main:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
