name = "Randomcreationstheme"
description = "Portfolio theme for Random Creations"
tags = ["portfolio", "responsive"]
features = ["responsive", "open-graph"]
min_version = "0.154.0"

[author]
  name = "@javoire"
  homepage = "https://github.com/javoire"
